armandoteran/aquarental

Gemfile, Gemfile.lock, app/models/user.rb, app/views/layouts/application.html.erb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20200711173114_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
I have add devise**. Please c**heck it! @armandoteran @jpcastiglioni
=> Add devise

app/controllers/equipments_controller.rb, app/models/booking.rb, app/models/equipment.rb, app/views/equipments/index.html.erb, config/routes.rb, test/controllers/equipments_controller_test.rb
=> Route controller index

Gemfile, Gemfile.lock, app/models/equipment.rb, db/seeds.rb
Agregue Faker e interpolacion con keyword para imagen
=> added Faker in seed2

app/controllers/bookings_controller.rb, app/controllers/reviews_controller.rb, app/models/booking.rb, app/views/bookings/index.html.erb, test/controllers/bookings_controller_test.rb, test/controllers/reviews_controller_test.rb
Added basic CRUD actions without considering nested routes.
=> Add reviews controller

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/index.html.erb, test/controllers/bookings_controller_test.rb
Added bookings/index.html.erb.
Setted total price before validation in booking.rb
=> Add bookings index

app/controllers/bookings_controller.rb, test/controllers/bookings_controller_test.rb
Added all CRUD actions, without any link to other pages.
=> Add bookings controller without links to other pages

app/views/equipments/index.html.erb, config/routes.rb, routes.txt
Todas las routes de equipment y booking planteadas en el sheets
=> Add equipment&booking resources to root

app/controllers/equipments_controller.rb, app/views/equipments/new.html.erb, app/views/equipments/show.html.erb
=> Add equipment new

app/controllers/equipments_controller.rb, app/views/equipments/show.html.erb
Add show page. Route to new booking form remaining.
=> Add equipments show

app/controllers/equipments_controller.rb
Removed Equipment.find from show action.
=> Remove unnecesary code

app/controllers/equipments_controller.rb, app/views/equipments/edit.html.erb, app/views/equipments/new.html.erb, app/views/equipments/show.html.erb
Added edit action in equipments controller.
Added form_for in edit page.
=> Add edit page

app/controllers/equipments_controller.rb, app/views/equipments/edit.html.erb, app/views/equipments/new.html.erb, app/views/equipments/show.html.erb
Action was already done! Just merge the branch!
=> Add equipments delete action

app/assets/stylesheets/components/_alert.scss, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
Se modifico el boton de crar publicacion para que en casos no autenticados redirija a sign_up
=> Modify navbar create only authenticated

db/seeds.rb
agregue campos mas personalizados al seed de equipment y review
=> Modify seed accurate images

app/views/equipments/new.html.erb
Finished new page for equipments.
=> Finished equipment new page

app/controllers/equipments_controller.rb, app/models/equipment.rb
=> Finished new and create action for equipments

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_cards.scss, app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/controllers/equipments_controller.rb, app/policies/application_policy.rb, app/policies/booking_policy.rb, app/policies/equipment_policy.rb, app/views/equipments/index.html.erb, app/views/shared/_navbar.html.erb, test/policies/booking_policy_test.rb, test/policies/equipment_policy_test.rb
Se agregaron todas las policies de Equipment
Se agregaron todas las policies de Booking salvo la del index, que esta seteada a true por default (hay que hace el scope pero eso mejor ya probarlo con el html)
=> Add authorization

app/policies/equipment_policy.rb, app/views/equipments/show.html.erb
Add authorization so only owner can edit / delete an equipment
=> Add authorization so only owner can edit / delete an equipment

Gemfile, Gemfile.lock, app/controllers/equipments_controller.rb, app/models/equipment.rb, app/views/shared/_navbar.html.erb
Agreguado:
- Search form en el app/views/shared/_navbar.html.erb 
```
<div class="container">
<%= form_tag equipments_path, method: :get do %>
<div class="d-flex">
<%= text_field_tag :query,
params[:query],
class: "form-control",
placeholder: "Buscar equipo"
%>
<%= submit_tag "Buscar", class: "btn btn-primary" %>
</div>
<% end %>
</div>
```
- Installe el gem pg_search
- Modifie el index en el equipments_controller para el pg_search
```def index
if params[:query].present?
@equipments = policy_scope(Equipment)
@equipments = Equipment.search_by(params[:query])
else
@equipments = Equipment.all
@equipments = policy_scope(Equipment)
end
end
```
=> Search bar

app/views/shared/_navbar.html.erb
Agregado:
- Nombre de la pagina arriba a la izquierda
- Nombre de la pagina es link
```   <div>
<ul class="navbar-nav mr-auto">
<li>
<%= link_to equipments_path do %>
<button type="button" class="btn btn-outline-primary mb-0">
<strong>Aqua</strong>RENTAL
</button>
<% end %>
</li>
</div> ```
- Boton publicar equipo movido a la derecha
P.S.: Creen que sea bueno agregar una line como "equipos acuaticos" debajo del link de inicio?
=> added site name and moved inicio link to the left

config/routes.rb
=> Add reviews routes

config/environments/development.rb, db/seeds.rb
Seed necesario para probar correctamente el booking.index
=> Revision seed add two clear users

db/migrate/20200722002434_remove_price_hour_from_equipments.rb, db/schema.rb, db/seeds.rb
**Recordar correr rails db:migrate en sus repos para que este cambio tome efecto!!!!!!!!!**
=> Removed column price-hour from Equipment

app/views/shared/_navbar.html.erb
Agregue ```sticky-top``` en line 1 para fijar la navbar.
=> added sticky-top in line 1

app/assets/stylesheets/components/_footer.scss, app/views/shared/_footer.html.erb
Agregado:
- background-color:white
- cambio de opacity para hacer los links mas visibles
=> Footer colour

app/policies/booking_policy.rb, app/views/equipments/show.html.erb
Agregado:
- owner no puede reservar su propio equipo en booking_policy.rb con un ```unless record.owner == user```
- solo se muestra booking form si current_user == owner con ```<% if current_user.id == @equipment.user_id %>``` en app/views/equpments/show.html.erb
=> Onwer cannot book their own equipment

app/models/equipment.rb, app/views/equipments/new.html.erb
Added container and drop down list for categories
=> Add style equipment new

app/assets/stylesheets/components/_footer.scss
=> footer fixed to bottom

app/views/equipments/show.html.erb
=> Add owner email

app/controllers/equipments_controller.rb, app/views/equipments/show.html.erb
Added equipments reviews, including content and rating
=> Add reviews in equipment show

app/controllers/equipments_controller.rb, app/policies/equipment_policy.rb, app/views/equipments/my.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
Agregado:
- ruta
- accion
- rights
- cards
=> Mis equipos

app/controllers/application_controller.rb, app/models/equipment.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/equipments/index.html.erb, app/views/equipments/my.html.erb, app/views/shared/_navbar.html.erb, config/environments/development.rb, db/migrate/20200724001119_add_img_url_to_user.rb, db/migrate/20200724001424_add_username_to_user.rb, db/schema.rb, db/seeds.rb
Added img_url to user model
Edited seed and views (equipment index and navbar) to use the db url.
=> Add custom fields to user

db/seeds.rb
Se volvieron a usar faker para datos y se fijaron las imagenes para /med/men/#{number}
=> Problem fixed

app/views/devise/registrations/edit.html.erb, app/views/shared/_navbar.html.erb
Agregado edit de profile y formato base
=> User can edit profile

app/controllers/bookings_controller.rb, app/controllers/reviews_controller.rb, app/policies/review_policy.rb, app/views/bookings/index.html.erb, app/views/bookings/show.html.erb
Agregado
- review form en booking#show
- condicion with state y date en booking#show
```<% if @booking.state == "BOOKED" && @booking.end_date < Date.today%>```
- volvi a agregar esto booking#index para poder ver el renter booking
```@as_renter_bookings```
=> New review

app/models/equipment.rb, app/views/equipments/new.html.erb
Fixed:
- not showing picture_url in form
- added before_save method in model
=> not showing pic url in form and added before_save in model
